import {
  ColumnType,
  Generated,
  Insertable,
  Selectable,
  Updateable,
} from 'kysely'

/**
 * Core data types for the scribe app
 */

/**
 * Unique identifier for a block (UUID format)
 */
export type BlockUuid = string

/**
 * Unique identifier for a version (UUID format)
 */
export type VersionUuid = string

/**
 * Type of block - currently only scribe/markdown is supported
 */
export type BlockType = 'scribe/markdown'

/**
 * User or device identifier that inserted a version
 */
export type Inserter = string

/**
 * A block represents a unit of content in the scribe app
 */
export interface Block {
  /**
   * Unique identifier for the block (UUID format)
   */
  block_uuid: BlockUuid

  /**
   * Type of the block
   */
  block_type: BlockType

  /**
   * Unique identifier for this version (UUID format)
   */
  version_uuid: VersionUuid

  /**
   * Identifier for the previous version (null for first version, UUID format)
   */
  prior_version_uuid: VersionUuid | null

  /**
   * Timestamp when this version was inserted
   */
  insert_datetime: Date

  /**
   * User or device that inserted this version
   */
  inserter: Inserter

  /**
   * The content of the block
   */
  body: string
}

/**
 * Database representation of a block (with proper types for database storage)
 */
export interface BlockRow {
  block_uuid: string
  block_type: string
  version_uuid: string
  prior_version_uuid: string | null
  insert_datetime: string // ISO string for database storage
  inserter: string
  body: string
}

/**
 * Database schema for the scribe app following Kysely best practices
 * 
 * This provides type-safe database access using Kysely.
 */

/**
 * Database representation of a block in the scribe app for Kysely
 * 
 * This interface describes the `block` table to Kysely. Table
 * interfaces should only be used in the `Database` type and never 
 * as a result type of a query. See the `BlockRecord`, `NewBlockRecord` and 
 * `BlockRecordUpdate` types below.
 */
export interface BlockRecordTable {
  /**
   * Unique identifier for the block (UUID format)
   * This is not generated by the database, but we mark it as Generated
   * because it should be provided by the application.
   */
  block_uuid: Generated<string>

  /**
   * Type of the block (currently only 'scribe/markdown' is supported)
   */
  block_type: string

  /**
   * Unique identifier for this version (UUID format)
   * This serves as the primary key for the table.
   */
  version_uuid: Generated<string>

  /**
   * Identifier for the previous version (null for first version, UUID format)
   */
  prior_version_uuid: string | null

  /**
   * Timestamp when this version was inserted
   * 
   * You can specify a different type for each operation (select, insert and
   * update) using the `ColumnType<SelectType, InsertType, UpdateType>`
   * wrapper. Here we define a column `insert_datetime` that is selected as
   * a `Date`, can optionally be provided as a `string` in inserts and
   * can never be updated:
   */
  insert_datetime: ColumnType<Date, string | undefined, never>

  /**
   * User or device that inserted this version
   */
  inserter: string

  /**
   * The content of the block
   */
  body: string
}

/**
 * The main database schema for the scribe app
 * 
 * For Kysely's type-safety and autocompletion to work, it needs to know your 
 * database structure. This requires a TypeScript `Database` interface, that 
 * contains table names as keys and table schema interfaces as values.
 */
export interface Database {
  /**
   * Table containing all block versions
   */
  block: BlockRecordTable
}

/**
 * You should not use the table schema interfaces directly. Instead, you should
 * use the `Selectable`, `Insertable` and `Updateable` wrappers. These wrappers
 * make sure that the correct types are used in each operation.
 *
 * Most of the time you should trust the type inference and not use explicit
 * types at all. These types can be useful when typing function arguments.
 */
export type BlockRecord = Selectable<BlockRecordTable>
export type NewBlockRecord = Insertable<BlockRecordTable>
export type BlockRecordUpdate = Updateable<BlockRecordTable>
