import {
  ColumnType,
  Generated,
  Insertable,
  Selectable,
  Updateable,
} from 'kysely'

/**
 * Core data types for the scribe app
 */

/**
 * Unique identifier for a block (UUID format)
 */
export type BlockUuid = string

/**
 * Unique identifier for a version (UUID format)
 */
export type VersionUuid = string

/**
 * Type of block - currently only scribe/markdown is supported
 */
export type BlockType = 'scribe/markdown'

/**
 * User or device identifier that inserted a version
 */
export type Inserter = string

/**
 * A block represents a unit of content in the scribe app
 */
export interface Block {
  /**
   * Unique identifier for the block (UUID format)
   */
  block_uuid: BlockUuid

  /**
   * Type of the block
   */
  block_type: BlockType

  /**
   * Unique identifier for this version (UUID format)
   */
  version_uuid: VersionUuid

  /**
   * Identifier for the previous version (null for first version, UUID format)
   */
  prior_version_uuid: VersionUuid | null

  /**
   * Timestamp when this version was inserted
   */
  insert_datetime: Date

  /**
   * User or device that inserted this version
   */
  inserter: Inserter

  /**
   * The content of the block
   */
  body: string
}

/**
 * Database representation of a block (with proper types for database storage)
 */
export interface BlockRow {
  block_uuid: string
  block_type: string
  version_uuid: string
  prior_version_uuid: string | null
  insert_datetime: string // ISO string for database storage
  inserter: string
  body: string
}

/**
 * Database representation of an indexed block (with proper types for database storage)
 */
export interface IndexedBlockRow {
  block_uuid: string
  version_uuid: string
  indexed: boolean
  last_indexed_at: string // ISO string for database storage
}

/**
 * Database representation of a block slug (with proper types for database storage)
 */
export interface BlockSlugRow {
  block_uuid: string
  slug: string
  title: string
  indexed_at: string // ISO string for database storage
}

/**
 * Database representation of a block tag (with proper types for database storage)
 */
export interface BlockTagRow {
  block_uuid: string
  tag: string
  indexed_at: string // ISO string for database storage
}

/**
 * Database schema for the scribe app following Kysely best practices
 * 
 * This provides type-safe database access using Kysely.
 */

/**
 * Database representation of a block in the scribe app for Kysely
 * 
 * This interface describes the `block` table to Kysely. Table
 * interfaces should only be used in the `Database` type and never 
 * as a result type of a query. See the `BlockRecord`, `NewBlockRecord` and 
 * `BlockRecordUpdate` types below.
 */
export interface BlockRecordTable {
  /**
   * Unique identifier for the block (UUID format)
   * This is not generated by the database, but we mark it as Generated
   * because it should be provided by the application.
   */
  block_uuid: Generated<string>

  /**
   * Type of the block (currently only 'scribe/markdown' is supported)
   */
  block_type: string

  /**
   * Unique identifier for this version (UUID format)
   * This serves as the primary key for the table.
   */
  version_uuid: Generated<string>

  /**
   * Identifier for the previous version (null for first version, UUID format)
   */
  prior_version_uuid: string | null

  /**
   * Timestamp when this version was inserted
   * 
   * You can specify a different type for each operation (select, insert and
   * update) using the `ColumnType<SelectType, InsertType, UpdateType>`
   * wrapper. Here we define a column `insert_datetime` that is selected as
   * a `Date`, can optionally be provided as a `string` in inserts and
   * can never be updated:
   */
  insert_datetime: ColumnType<Date, string | undefined, never>

  /**
   * User or device that inserted this version
   */
  inserter: string

  /**
   * The content of the block
   */
  body: string
}

/**
 * Database representation of an indexed block for Kysely
 */
export interface IndexedBlockRecordTable {
  /**
   * Unique identifier for the block (UUID format)
   */
  block_uuid: Generated<string>

  /**
   * Version UUID of the authoritative version
   */
  version_uuid: string

  /**
   * Flag indicating if this block has been indexed
   */
  indexed: boolean

  /**
   * Timestamp of last index update
   */
  last_indexed_at: string
}

/**
 * Database representation of a block slug for Kysely
 */
export interface BlockSlugRecordTable {
  /**
   * Unique identifier for the block (UUID format)
   */
  block_uuid: Generated<string>

  /**
   * The URL-friendly slug derived from the block title
   */
  slug: string

  /**
   * The original title of the block
   */
  title: string

  /**
   * Timestamp when this slug was indexed
   */
  indexed_at: string
}

/**
 * Database representation of block tags for Kysely
 */
export interface BlockTagRecordTable {
  /**
   * Unique identifier for the block (UUID format)
   */
  block_uuid: Generated<string>

  /**
   * The tag extracted from the block
   */
  tag: string

  /**
   * Timestamp when this tag was indexed
   */
  indexed_at: string
}

/**
 * Database representation of authoritative versions (non-synchronized)
 * Maps block UUIDs to their authoritative (latest) version UUIDs
 */
export interface AuthoritativeVersionRecordTable {
  /**
   * Unique identifier for the block (UUID format)
   */
  block_uuid: Generated<string>

  /**
   * Version UUID of the authoritative version
   */
  version_uuid: string

  /**
   * Timestamp when this mapping was last updated
   */
  indexed_at: string
}

/**
 * The main database schema for the scribe app
 * 
 * For Kysely's type-safety and autocompletion to work, it needs to know your 
 * database structure. This requires a TypeScript `Database` interface, that 
 * contains table names as keys and table schema interfaces as values.
 */
export interface Database {
  /**
   * Table containing all block versions
   */
  block: BlockRecordTable

  /**
   * Table containing indexing status for blocks (non-synchronized)
   */
  indexed_block: IndexedBlockRecordTable

  /**
   * Table containing block slugs (non-synchronized)
   */
  block_slug: BlockSlugRecordTable

  /**
   * Table containing block tags (non-synchronized)
   */
  block_tag: BlockTagRecordTable

  /**
   * Table containing authoritative version mappings (non-synchronized)
   */
  authoritative_version: AuthoritativeVersionRecordTable
}

/**
 * You should not use the table schema interfaces directly. Instead, you should
 * use the `Selectable`, `Insertable` and `Updateable` wrappers. These wrappers
 * make sure that the correct types are used in each operation.
 *
 * Most of the time you should trust the type inference and not use explicit
 * types at all. These types can be useful when typing function arguments.
 */
export type BlockRecord = Selectable<BlockRecordTable>
export type NewBlockRecord = Insertable<BlockRecordTable>
export type BlockRecordUpdate = Updateable<BlockRecordTable>

/**
 * Type for a block with its authoritative version information
 */
export interface BlockWithVersion extends Block {
  /**
   * The authoritative version UUID for this block
   */
  authoritative_version_uuid: VersionUuid
}

/**
 * Type for a block with its slug
 */
export interface BlockWithSlug extends Block {
  /**
   * The URL-friendly slug for this block
   */
  slug: string
  
  /**
   * The title of the block
   */
  title: string
}

/**
 * Type for a block with its tags
 */
export interface BlockWithTags extends Block {
  /**
   * Array of tags for this block
   */
  tags: string[]
}

/**
 * Type for a complete indexed block with all metadata
 */
export interface IndexedBlock extends BlockWithVersion, BlockWithSlug, BlockWithTags {}
