// Comprehensive tests for tributary-client
import { describe, it, expect, beforeEach } from 'vitest';
import { TributaryClient, TributaryServer, createTestServer, FakeServer } from '../src/index';
import nacl from 'tweetnacl';
import * as base64url from 'urlsafe-base64';

describe('TributaryClient Components', () => {
  let testServer: any;
  let testKeyPair: nacl.SignKeyPair;
  let testPrivateKeyBase64: string;
  let testPublicKeyBase64: string;

  beforeEach(() => {
    testServer = createTestServer();
    testKeyPair = nacl.sign.keyPair();
    testPrivateKeyBase64 = base64url.encode(Buffer.from(testKeyPair.secretKey));
    testPublicKeyBase64 = base64url.encode(Buffer.from(testKeyPair.publicKey));
  });

  it('should create a TributaryClient instance with base64 private key', () => {
    const client = new TributaryClient({
      server: testServer,
      privateKey: testPrivateKeyBase64,
      collectionId: 'test-collection'
    });
    
    expect(client).toBeInstanceOf(TributaryClient);
  });

  it('should create a TributaryClient instance with Uint8Array private key', () => {
    const client = new TributaryClient({
      server: testServer,
      privateKey: testKeyPair.secretKey,
      collectionId: 'test-collection'
    });
    
    expect(client).toBeInstanceOf(TributaryClient);
  });

  it('should create a TributaryServer instance', () => {
    const server = new TributaryServer('http://localhost:8080');
    expect(server).toBeInstanceOf(TributaryServer);
  });

  it('should create a FakeServer instance', () => {
    const fakeServer = new FakeServer();
    expect(fakeServer).toBeInstanceOf(FakeServer);
  });

  it('should store and retrieve a blob using FakeServer', async () => {
    // Only run this test for FakeServer
    if (testServer.constructor.name !== 'FakeServer') {
      expect(true).toBe(true); // Skip test for real server
      return;
    }
    
    const data = new TextEncoder().encode('Hello, Tributary!');
    const bodyHash = await computeHash(data);
    const priorHash = '';
    
    // Compute hash as SHA256(priorHash + bodyHash) - same as client implementation
    const concatenated = `${priorHash}${bodyHash}`;
    const hash = await computeHash(new TextEncoder().encode(concatenated));
    
    // Create the data to be signed (just the hash)
    const dataToSignBytes = new TextEncoder().encode(hash);
    
    // Sign the data
    const signatureBytes = nacl.sign.detached(dataToSignBytes, testKeyPair.secretKey);
    const signature = base64url.encode(Buffer.from(signatureBytes));
    
    // Store the blob (note: ID is now auto-generated by the server)
    const result = await testServer.storeBlob(
      testPublicKeyBase64,
      data,
      hash,
      priorHash,
      signature,
      1
    );
    
    expect(result).toBe(true);
    
    // Retrieve the blob using the auto-generated ID format
    const blobId = `${testPublicKeyBase64}:1`;
    const retrievedBlob = await testServer.retrieveBlob(testPublicKeyBase64, blobId);
    
    expect(retrievedBlob).not.toBeNull();
    expect(retrievedBlob!.id).toBe(blobId);
    expect(retrievedBlob!.pubkey).toBe(testPublicKeyBase64);
    expect(retrievedBlob!.hash).toBe(hash);
    expect(retrievedBlob!.priorHash).toBe(priorHash);
    expect(retrievedBlob!.sequenceNumber).toBe(1);
    expect(retrievedBlob!.data).toEqual(data);
  });

  it('should not allow storing the same blob twice', async () => {
    // Only run this test for FakeServer
    if (testServer.constructor.name !== 'FakeServer') {
      expect(true).toBe(true); // Skip test for real server
      return;
    }
    
    const data = new TextEncoder().encode('Hello, Tributary!');
    const bodyHash = await computeHash(data);
    const priorHash = '';
    
    // Compute hash as SHA256(priorHash + bodyHash) - same as client implementation
    const concatenated = `${priorHash}${bodyHash}`;
    const hash = await computeHash(new TextEncoder().encode(concatenated));
    
    // Create the data to be signed (just the hash)
    const dataToSignBytes = new TextEncoder().encode(hash);
    
    // Sign the data
    const signatureBytes = nacl.sign.detached(dataToSignBytes, testKeyPair.secretKey);
    const signature = base64url.encode(Buffer.from(signatureBytes));
    
    // Store the blob first time
    const result1 = await testServer.storeBlob(
      testPublicKeyBase64,
      data,
      hash,
      priorHash,
      signature,
      1
    );
    
    expect(result1).toBe(true);
    
    // Try to store the same blob again (with same sequence number)
    const result2 = await testServer.storeBlob(
      testPublicKeyBase64,
      data,
      hash,
      priorHash,
      signature,
      1
    );
    
    expect(result2).toBe(false); // Should return false for conflict
  });
  
  it('should ensure server persistence before local execution', async () => {
    const client = new TributaryClient({
      server: testServer,
      privateKey: testPrivateKeyBase64,
      collectionId: 'test-collection'
    });
    
    // This would test that write operations ensure server persistence
    // For now, we'll just verify the client was created correctly
    expect(client).toBeInstanceOf(TributaryClient);
  });
});

// Helper functions for testing
async function computeHash(data: Uint8Array): Promise<string> {
  const hashBuffer = await crypto.subtle.digest('SHA-256', data.buffer as ArrayBuffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}
