/**
 * Cross-implementation compatibility test:
 * Verifies that the server-side verifyMerkleProof (supabase/functions/shared/crypto.ts)
 * correctly validates proofs generated by the client-side merkletreejs helpers
 * (tributary-client/src/tributaryBlob.ts).
 *
 * We port the server's verifyMerkleProof logic here using the client's computeHash
 * to prove the two implementations are compatible.
 */
import { describe, it, expect } from 'vitest'
import {
  computeChunkHash,
  buildChunkTree,
  getChunkProof,
  verifyChunkProof,
  type ProofEntry,
} from '../src/tributaryBlob.js'
import { computeHash } from '../src/hashUtils.js'

// --- Server-side verifyMerkleProof, ported verbatim from crypto.ts ---
// Uses the client's computeHash (same SHA256 hex implementation).

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2)
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.substr(i * 2, 2), 16)
  }
  return bytes
}

async function serverVerifyMerkleProof(
  rootHash: string,
  chunkHash: string,
  proof: Array<{ position: 'left' | 'right'; data: string }>,
): Promise<boolean> {
  let hash = chunkHash

  for (const step of proof) {
    const left = step.position === 'left' ? step.data : hash
    const right = step.position === 'left' ? hash : step.data

    const leftBuf = hexToBytes(left)
    const rightBuf = hexToBytes(right)
    const combined = new Uint8Array(leftBuf.length + rightBuf.length)
    combined.set(leftBuf)
    combined.set(rightBuf, leftBuf.length)

    hash = await computeHash(combined)
  }

  return hash === rootHash
}

// --- Tests ---

describe('server verifyMerkleProof ↔ client merkletreejs compatibility', () => {
  it('single chunk: server accepts client proof (empty proof)', async () => {
    const chunk = new TextEncoder().encode('single chunk data')
    const hash = await computeChunkHash(chunk)
    const { root, tree } = buildChunkTree([hash])
    const proof = getChunkProof(tree, hash)

    // Client says valid
    expect(verifyChunkProof(root, hash, proof)).toBe(true)

    // Server says valid
    expect(await serverVerifyMerkleProof(root, hash, proof)).toBe(true)
  })

  it('two chunks: server accepts both client proofs', async () => {
    const chunks = [
      new TextEncoder().encode('first chunk of data'),
      new TextEncoder().encode('second chunk of data'),
    ]
    const hashes = await Promise.all(chunks.map(c => computeChunkHash(c)))
    const { root, tree } = buildChunkTree(hashes)

    for (let i = 0; i < hashes.length; i++) {
      const proof = getChunkProof(tree, hashes[i])

      // Client says valid
      expect(verifyChunkProof(root, hashes[i], proof)).toBe(true)

      // Server says valid
      expect(await serverVerifyMerkleProof(root, hashes[i], proof)).toBe(true)
    }
  })

  it('three chunks: server accepts all client proofs', async () => {
    const chunks = [
      new TextEncoder().encode('chunk-alpha'),
      new TextEncoder().encode('chunk-beta'),
      new TextEncoder().encode('chunk-gamma'),
    ]
    const hashes = await Promise.all(chunks.map(c => computeChunkHash(c)))
    const { root, tree } = buildChunkTree(hashes)

    for (let i = 0; i < hashes.length; i++) {
      const proof = getChunkProof(tree, hashes[i])

      expect(verifyChunkProof(root, hashes[i], proof)).toBe(true)
      expect(await serverVerifyMerkleProof(root, hashes[i], proof)).toBe(true)
    }
  })

  it('four chunks: server accepts all client proofs', async () => {
    const chunks = [
      new TextEncoder().encode('chunk-0'),
      new TextEncoder().encode('chunk-1'),
      new TextEncoder().encode('chunk-2'),
      new TextEncoder().encode('chunk-3'),
    ]
    const hashes = await Promise.all(chunks.map(c => computeChunkHash(c)))
    const { root, tree } = buildChunkTree(hashes)

    for (let i = 0; i < hashes.length; i++) {
      const proof = getChunkProof(tree, hashes[i])

      expect(verifyChunkProof(root, hashes[i], proof)).toBe(true)
      expect(await serverVerifyMerkleProof(root, hashes[i], proof)).toBe(true)
    }
  })

  it('server rejects tampered chunk hash', async () => {
    const chunks = [
      new TextEncoder().encode('good chunk A'),
      new TextEncoder().encode('good chunk B'),
    ]
    const hashes = await Promise.all(chunks.map(c => computeChunkHash(c)))
    const { root, tree } = buildChunkTree(hashes)
    const proof = getChunkProof(tree, hashes[0])

    const tamperedHash = await computeChunkHash(new TextEncoder().encode('tampered'))

    // Client rejects
    expect(verifyChunkProof(root, tamperedHash, proof)).toBe(false)

    // Server rejects
    expect(await serverVerifyMerkleProof(root, tamperedHash, proof)).toBe(false)
  })

  it('server rejects wrong root hash', async () => {
    const chunks = [
      new TextEncoder().encode('data X'),
      new TextEncoder().encode('data Y'),
    ]
    const hashes = await Promise.all(chunks.map(c => computeChunkHash(c)))
    const { root, tree } = buildChunkTree(hashes)
    const proof = getChunkProof(tree, hashes[0])

    const wrongRoot = 'a'.repeat(64)

    expect(verifyChunkProof(wrongRoot, hashes[0], proof)).toBe(false)
    expect(await serverVerifyMerkleProof(wrongRoot, hashes[0], proof)).toBe(false)
  })

  it('server rejects swapped proof (proof for chunk 0 used with chunk 1)', async () => {
    const chunks = [
      new TextEncoder().encode('alpha data'),
      new TextEncoder().encode('beta data'),
    ]
    const hashes = await Promise.all(chunks.map(c => computeChunkHash(c)))
    const { root, tree } = buildChunkTree(hashes)

    // Get proof for chunk 0, but try to verify chunk 1 with it
    const proof0 = getChunkProof(tree, hashes[0])

    expect(verifyChunkProof(root, hashes[1], proof0)).toBe(false)
    expect(await serverVerifyMerkleProof(root, hashes[1], proof0)).toBe(false)
  })

  it('larger tree (8 chunks) — all proofs valid on both sides', async () => {
    const chunks = Array.from({ length: 8 }, (_, i) =>
      new TextEncoder().encode(`chunk number ${i} with some content`)
    )
    const hashes = await Promise.all(chunks.map(c => computeChunkHash(c)))
    const { root, tree } = buildChunkTree(hashes)

    for (let i = 0; i < hashes.length; i++) {
      const proof = getChunkProof(tree, hashes[i])

      expect(verifyChunkProof(root, hashes[i], proof)).toBe(true)
      expect(await serverVerifyMerkleProof(root, hashes[i], proof)).toBe(true)
    }
  })
})
